config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root to: "tests#index"

  devise_for :users, path: :auth, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admin, path: :admin, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :gitgists, only: %i[create]
  resources :feedbacks, only: %i[new create edit]
  resources :user_badges, only: :index

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :result, only: %i[show update index] do
    member do
      get :again
      get :info
    end
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true
  before_validation :before_validation_set_new_questions, on: :create
  before_validation :update_result, on: [:update]
  # before_validation :set_current_question, on: [:create, :update]

  SUCCESS_SCORE = 85

  def test_passed?
    pass_test
  end

  def passed_test?
    current_question.nil?
  end

  def index_question
    total_questions - questions.count
  end

  def again
    before_validation_set_new_questions
    self.attempts += 1
    save!
  end

  def accept(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
  end

  private

  def set_poins
    self.point = self.total_questions > 0 ? ((self.correct_questions.to_f / self.total_questions.to_f) * 100) : 0
  end

  def array_questions
    test.questions.pluck(:id)
  end

  def before_validation_set_new_questions
    arr = test.array_questions_valid
    if arr.present?
      self.correct_questions = 0
      self.questions = arr.sort_by { rand }
      self.total_questions = arr.count
      self.start_test = DateTime.current
      self.end_test = start_test + (self.test.duration).minutes
    end
  end

  def update_result
    if self.questions.empty? || (self.test.duration > 0 && self.end_test < DateTime.current)
      set_poins
      self.pass_test = self.point >= SUCCESS_SCORE ? true : false
      self.questions = []
      self.current_question = nil
    else
      set_current_question
    end
  end

  def set_current_question
    self.current_question = Question.find(questions[0])
    self.questions.shift
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: :User
  belongs_to :category
  has_many :results, dependent: :destroy
  has_many :users, through: :results
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions
  validates :title, presence: true

  validates :level, presence: true,
                    numericality: { only_integer: true },
                    uniqueness: { scope: :title }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY.to_i) }
  scope :level, ->(level) { where(level: level) }
  scope :category_of, ->(name) {
          joins(:category).where(categories: { title: name })
        }
  scope :valid, -> { joins(:answers).where("answers.correct = ?", true).group("tests.id") }
  scope :passed, ->{ joins(:results).where("results.pass_test >= ?", true) }

def self.post_test
  valid.where(post: :true)

end

  def self.category_order_desc(category)
    category_of(category).order(title: :desc)
  end

  def array_questions
    self.questions.pluck(:id)
  end

  def array_questions_valid
    self.questions.valid.pluck(:id)
  end
end

app/controllers/result_controller.rb
class ResultController < ApplicationController
  before_action :set_result, only: [:show, :again, :update, :info]

  def show

  end

  def index
    # // тут дожно быть список тестов пройденные пользователем
  end

  def again
    @result.again
    redirect_to result_path(@result)
  end

  def info

  end

  def update
    @result.accept(params[:answer_ids])
    @result.save
    if @result.passed_test?
      BadgesService.new(@result).give if @result.test_passed?
      TestsMailer.completed_test(@result).deliver_now
      redirect_to info_result_path(@result)
    else
      render :show
    end
  end

  private

  def set_result
    @result = Result.find(params[:id])
  end

  def result_params
    params.require(:result).permit()
  end
end

app/helpers/result_helper.rb
module ResultHelper
  def duration_seconds(result)
   seconds = (result.end_test - DateTime.current).seconds

   seconds>= 0 ? seconds : 0
  end

  def percent_completed_test(result)
    ((result.index_question.to_f / result.test.questions.length) * 100).to_i
  end

  def question_title(result)
    "Questions № #{result.index_question} #{result.current_question.body} question"
  end

  def attempt_title(result)
    "Attempts №#{result.attempts}"
  end

  def show_result_message(result)
    if result.test_passed?
      css_class = "success"
      text = "SUCCESS! Test was completed!"
    else
      css_class = "fail"
      text = "FAIL! Please try again."
    end
    result_body = "<div class = #{css_class}> Scope #{result.point} #{text}"

    safe_join([raw(result_body)])
  end
end

app/views/result/_form.html.erb
<%= form_with url: result_path(@result), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids,
                                  @result.current_question.answers,
                                  :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p> <%= link_to t("button.gist"), gitgists_path(result: @result.id), method: :post %> </p>
  <p><%= form.submit "Next" %></p>
<% end %>

app/views/result/_scope.html.erb
<h2> Scope <%= @result.point %></h2>
<h1>The <%= @result.test.title %> Test was Completed!</h1>
<p>
 <%= "Number of All Questions in Test #{@result.total_questions}" %> <br>
 <%= "Questions with Correct Answers: #{@result.correct_questions} " %>
</p>
<% cl = @result.point > 85 ? "success" : "fail" %>
<h2 class="<%= cl %>"> <%= show_result_message(@result) %> 
<%= link_to "Try Again", again_result_path(@result) %></h2><br>
<%= link_to "All Tests", tests_path, method: "get" %>

app/views/result/info.html.erb
<h2> Scope <%= @result.point %></h2>
<h1>The <%= @result.test.title %> Test was Completed!</h1>
<p>
 <%= "Number of All Questions in Test #{@result.total_questions}" %> <br>
 <%= "Questions with Correct Answers: #{@result.correct_questions} " %>
</p>
<h2> <%= show_result_message(@result) %> 
<%= link_to "Try Again", again_result_path(@result) %></h2><br>
<%= link_to "All Tests", tests_path, method: "get" %>

app/views/result/show.html.erb
<h1>Passing the <%= @result.test.title %> Test</h1>
<%= render partial: 'shared/timer', locals: {duration: duration_seconds(@result)} if @result.test.duration > 0 %>
<%= render partial: 'shared/progress', locals: {percent: percent_completed_test(@result)} %>
<h3><%= attempt_title(@result) %> </h3>
<h2><%= question_title(@result) %> </h2>
<h2><%=  %> </h2>
<%= render "form" %>