config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root to: "tests#index"

  devise_for :users, path: :auth, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admin, path: :admin, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :gitgists, only: %i[create]
  resources :feedbacks, only: %i[new create edit]
  resources :user_badges, only: :index

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :result, only: %i[show update index] do
    member do
      get :again
      get :info
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  validates :name, presence: true
  validates :img, presence: true
  validates :code, presence: true

  scope :for_code, ->(code) { where(code: code) }
  scope :for_text, ->(text) { where(text: text) }

  def self.code_jobs
    select(:code).group("code").pluck(:code)
  end

  def self.for_code_text(code, text)
    for_code(code).for_text(text)
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path, flash: { success: "Badge was succesfuly create" }
    else
      render :new
    end
  end

  def destroy
    redirect_to admin_badges_path, alert: "Badge was succesfuly delete" if @badge.destroy
  end
end

private

def set_badge
  @badge = Badge.find(params[:id])
end

def badge_params
  params.require(:badge).permit(:name, :img, :code, :text)
end

app/helpers/badges_helper.rb
module BadgesHelper
  ARRAY_IMG = [["Рисунок 1", "bi-bookmark-star "],
               ["Рисунок 2", "bi-star"],
               ["Рисунок 3", "bi-stars"],
               ["Рисунок 4", "bi-book"]]


end

app/views/admin/badges/_badge.html.erb
<div class="col">
  <div class="card text-center" >
    <h5 class="card-header "><%= badge.name %></h5>
    <div class="card-body">
      <%= class_img(badge.img) %>
    </div>
    <div class="card-footer" >
    </div>
    <div class="d-grid gap-2 ">
      <%= button_to t("button.edit"), edit_admin_badge_path(badge), method: :get, class: "btn btn-primary col-12"  %>
      <%= button_to t("button.delete"), admin_badge_path(badge), method: :delete,
                                                    class: "btn btn-primary col-12",
                                               data: { confirm: t("button.confirm") } %>
    </div>
  </div>
</div>

app/views/admin/badges/_form.html.erb
<div class="card-subtitle  border rounded p-3 border-info">
  <%= form_with(model: [:admin, @badge], local: true) do |form| %>
    <%#= form_with(model: @badge, url: admin_badges_path, local: true) do |form| %>
      <%= render "shared/errors", object: @badge %>
      <p>
        <%= form.label :name %>
        <%= form.text_field :name, id: :badge_name %>
      </p>
      <br>
      <p>
        <%= form.label :img %>
        <%= form.select :img, select_img, id: :badge_img %>
      </p>
      <br>
      <p>
        <%= form.label :code %>
        <%= form.select :code , select_code , id: :badge_code %>
      </p>
      <br>
      <p>
        <%= form.label :text %>
        <%= form.text_field :text, id: :badge_text %>
      </p>
      <br>
      <%= form.submit t('button.submit'), class: 'btn btn-outline-primary' %>
    <% end %>
  </div>

app/views/admin/badges/edit.html.erb
<h1><%= t("text.edit") %></h1>
<% array_code = BadgesService.list_service.to_a %>
<%= render partial: "form", locals: { select_code: array_code, select_img: BadgesHelper::ARRAY_IMG } %>

app/views/admin/badges/index.html.erb
<h1> <%= t("badge.text.header") %> </h1>
<%= render 'shared/errors', object: @badge %>
<p>
  <%=  button_to t("button.new"), new_admin_badge_path, method: :get, class: "btn btn-primary" %>
</p>
<div class="row row-cols-6">
  <%= render @badges %>
</div>

app/views/admin/badges/new.html.erb
<h1><%= t("text.new") %></h1>
<% array_code = BadgesService.list_service.to_a %>
<%= render partial: "form", locals: { select_code: array_code, select_img: BadgesHelper::ARRAY_IMG } %>