config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root to: "tests#index"

  devise_for :users, path: :auth, path_names: { sign_in: :login, sign_out: :logout }
  devise_for :admin, path: :admin, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :gitgists, only: %i[create]
  resources :feedbacks, only: %i[new create edit]
  resources :user_badges, only: :index

  namespace :admin do
    resources :badges
    resources :gists, only: :index
    resources :tests, shallow: true do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end

  resources :result, only: %i[show update index] do
    member do
      get :again
      get :info
    end
  end
end

app/views/layouts/_header.html.erb
<header class="p-1 bg-dark text-white">
  <%= render "layouts/navigation"%>
</header>

app/views/layouts/_navigation.html.erb
<div class="container-fluid">
  <nav class="d-flex justify-content-between align-items-stretch">
    <%= link_to "Test Guru", root_path, class: "navbar-brand ms-5" %>
    <ul class="nav col-8 justify-content-center mb-md-0  ">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Test
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to t("menu.hard"), root_path, class: "dropdown-item" %></li>
          <li><%= link_to t("menu.medium"), root_path, class: "dropdown-item" %></li>
          <li><%= link_to t("menu.light"), root_path, class: "dropdown-item" %></li>
        </ul>
      </li>
      <li class="nav-item">
        <%= link_to t("menu.mybadge"), user_badges_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t("menu.feedback"), new_feedback_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="nav nav col-3" >
      <li class="nav-item" >
        <%= render "shared/lang" %>
      </li>
      <li class="nav-item" >
        <%= render "shared/login" %>
      </li>
    </ul>
  </nav>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "layouts/admin/header" %>
    <%= render "shared/flash" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "shared/flash" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>